### ISSUE TITLE
Update Gatsby version for not getting TypeError: Data must be a string or a buffer

### ISSUE THREAD

**Issue by andresgutgon** [datocms/gatsby-portfolio#1]
Hi, I started today using Gatsby + DatoCMS based on this boilerplate. When I tried to run `yarn build` I got this error: https://github.com/gatsbyjs/gatsby/issues/1659

Run `yarn build` and 💥 
```
crypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at Hash.update (crypto.js:74:16)
```

### Solution
Just update `gatsby` dependency to `1.9.164` or newer and the error is gone

I hope it helps someone

**Comment by stefanoverna** [comment]
Thanks, updated!
