### ISSUE TITLE
Sanitized HTML

### ISSUE THREAD

**Issue by insuusvenerati** [datocms/gatsby-portfolio#13]
Howdy! 
This starter uses `dangerouslySetInnerHTML`. I could not find it while searching but is the data sanitized?

**Comment by matjack1** [comment]
Hey @insuusvenerati sanitized in what sense exactly? In any case it's data coming from our API, so it's either markdown rendered as HTML or HTML that was previously saved in our database. We sanitize before saving, but depends what you are looking for :)

I'm closing for now, feel free to reopen or add more information if you need to!
