### ISSUE TITLE
Host The Project On GitHub Pages

### ISSUE THREAD

**Issue by AdemHodzic** [datocms/gatsby-portfolio#14]
I'm sure this is an awesome project but not everybody has time to clone the repo, install dependencies and serve it locally. 

Can you host a demo on something like GitHub Pages?

**Comment by stefanoverna** [comment]
Just click the button "Start free project" and we'll take care of the rest! 
https://www.datocms.com/marketplace/starters/gatsby-portfolio

There's also a preview here: https://adoring-carson-24f43a.netlify.com/
