### ISSUE TITLE
The portfolio template is not available 

### ISSUE THREAD

**Issue by ahmedelgabri** [datocms/gatsby-portfolio#2]
When clicking this URL & trying to create a site from that template I get this error.

> This repo contains a working static website written with Gatsby, integrated with content coming from **this DatoCMS administrative area.**

<img width="1792" alt="screen shot 2018-02-08 at 21 16 58" src="https://user-images.githubusercontent.com/63876/35995994-75e778dc-0d15-11e8-8598-9cc45a1a7166.png">

**Comment by stefanoverna** [comment]
Fixed, thanks @ahmedelgabri!
