### ISSUE TITLE
error Cannot read property 'allDatoCmsWork' of undefined

### ISSUE THREAD

**Issue by braco** [datocms/gatsby-portfolio#3]
`yarn develop` yields this:

```
error Cannot read property 'allDatoCmsWork' of undefined


  TypeError: Cannot read property 'allDatoCmsWork' of undefined

  - gatsby-node.js:19 graphql.then.result
    /private/var/www/project/gatsby-node.js:19:19

  - util.js:16 tryCatcher
    [project]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [project]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [project]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [project]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [project]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [project]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [project]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'allDatoCmsWork' of undefined

  - gatsby-node.js:19 graphql.then.result
    /private/var/www/project/gatsby-node.js:19:19

  - util.js:16 tryCatcher
    [project]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [project]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [project]/[bluebird]/js/release/promise.js:569:18

  - promise.js:606 Promise._settlePromiseCtx
    [project]/[bluebird]/js/release/promise.js:606:10

  - async.js:138 Async._drainQueue
    [project]/[bluebird]/js/release/async.js:138:12

  - async.js:143 Async._drainQueues
    [project]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [project]/[bluebird]/js/release/async.js:17:14

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Also, needed to run a `yarn upgrade` since some packages were out of date, but I was getting similar errors before.

**Comment by ovsw** [comment]
@braco  Having a similar problem, opened a separate issue.  did you  ever manage to fix this?

**Comment by braco** [comment]
Nope, sorry, moved over to Wordpress for the CMS

**Comment by djclarkson** [comment]
Same issue.

**Comment by matjack1** [comment]
Hello @braco and @djclarkson sorry for the long delay.

Have you first set up the project in your DatoCMS area using this template: https://dashboard.datocms.com/projects/new-from-template/static-website/gatsby-portfolio ?

I'll update the README to make the step clearer. If you don't have the same schema on DatoCMS's side you won't be able to run this project.

**Comment by matjack1** [comment]
This is the guide I've written to make the steps more clear and meaningful: https://www.datocms.com/docs/static-generators/gatsbyjs

I'm closing for now but please reopen if that wasn't your issue or if you still have any doubt.

**Comment by zidski** [comment]
Hello @matjack1, I've followed your instructions, but still get an error:
**Cannot read property 'allDatoCmsWork' of undefined**

**Comment by matjack1** [comment]
@zidski can you paste a bit more context about the error that you are getting?

Did you populate the `.env` file with your DatoCMS token?

**Comment by zidski** [comment]
@matjack1 I've created an .env file and added the read-only token. I have used your demo setup in DatoCms. And when I run 'yarn develop' it brings back the error 

There was an error in your GraphQL query:

Cannot query field "allDatoCmsWork" on type "Query".

UNHANDLED REJECTION Cannot read property 'allDatoCmsWork' of undefined

TypeError: Cannot read property 'allDatoCmsWork' of undefined

**Comment by zidski** [comment]
@matjack1 I've just added the token straight into the gatsby-config.js and its worked, not sure why it isn't reading the .env file.

**Comment by matjack1** [comment]
hey @zidski I've just tried and works fine here. Can you please specify what you've entered in the .env file? Just to be sure.

And also, which version of Node and operating system are you on?

**Comment by zubairrauf** [comment]
@zidski In the .env file put the API key without quotes. 
Like:   DATO_API_TOKEN=abc123
