### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by ovsw** [datocms/gatsby-portfolio#4]
1. Did the demo install from the DatoCMS control panel. 
2.  Automated install and publish to netlify went ok, site working on netlify. 
3.  cloned the repo locally,
4. did `yarn install`,
5. created .env with API key.
6. `yarn develop` passed but with error in console:
```
GraphQL Error Unknown field `resize` on type `[DatoCmsAsset]`
file: C:/Dev/datocms-gatsby/src/templates/work.js

   1 |
   2 |   query WorkQuery($slug: String!) {
   3 |     datoCmsWork(slug: { eq: $slug }) {
   4 |       seoMetaTags {
   5 |         ...GatsbyDatoCmsSeoMetaTags
   6 |       }
   7 |       title
   8 |       excerpt
   9 |       gallery {
> 10 |         resize(height: 200, imgixParams: { fm: "jpg", auto: "compress" }) {
     |         ^
  11 |           src
  12 |         }
  13 |       }
  14 |       descriptionNode {
  15 |         childMarkdownRemark {
  16 |           html
  17 |         }
  18 |       }
  19 |       coverImage {
  20 |         url
```
7. on http://localhost:8000/ i get:

```
TypeError: Cannot read property 'datoCmsSite' of undefined
```
```
new TemplateWrapper
C:/Dev/datocms-gatsby/src/layouts/index.js:11
    8 | const TemplateWrapper = ({ children, data }) => (
    9 |   <div className="container">
   10 |     <HelmetDatoCms
 > 11 |       favicon={data.datoCmsSite.faviconMetaTags}
   12 |       seo={data.datoCmsHome.seoMetaTags}
   13 |     />
   14 |     <div className="container__sidebar">
```

Running the GraphQL query from index.js in GraphiQL, I get:
```
{
  "errors": [
    {
      "message": "Unknown fragment \"GatsbyDatoCmsFaviconMetaTags\".",
      "locations": [
        {
          "line": 7,
          "column": 12
        }
      ]
    },
    {
      "message": "Unknown fragment \"GatsbyDatoCmsSeoMetaTags\".",
      "locations": [
        {
          "line": 12,
          "column": 12
        }
      ]
    }
  ]
}
```
Please advise.

**Comment by matjack1** [comment]
Hey @ovsw I'm a bit late to this party, maybe you've solved your issue already. But I've tried just now and I cannot replicate. I can see that you are running on Windows, maybe it has issues, I haven't tried there yet.

Not sure if possible but could you try on a Linux box as well? Or I might try on Windows myself soon, just checking you are trying with the latest version of our portfolio project.

**Comment by matjack1** [comment]
@ovsw I've tried now on Windows 10 and it works here. I cannot reproduce your problem unfortunately.

If you are still interested you can try with the updated versions or maybe provide a bit more info on Win version and Node version?

Thanks!
