### ISSUE TITLE
Disappearing sidebar when "About" is clicked

### ISSUE THREAD

**Issue by ahmed-belhadj** [datocms/gatsby-portfolio#5]
Sidebar is disappearing when "About" is clicked.

Fresh install: https://objective-aryabhata-031fcb.netlify.com/

vs.

Demo link from README.md: https://cranky-edison-12166d.netlify.com/

**Comment by ahmed-belhadj** [comment]
Seems to be working when going back and using a43e3676ec5806bc33d0fde5155e90a0f731f3af

**Comment by matjack1** [comment]
Thank you @ahmed-belhadj I've just pushed a fix on master!
