### ISSUE TITLE
Doenst run on codesandbox.io

### ISSUE THREAD

**Issue by clockshark** [datocms/gatsby-portfolio#9]
Doenst run on codesandbox.io or gitpod. I added my own .env key as well and matched the fields.

**Comment by matjack1** [comment]
hey @clockshark, have a look at the screenshots below on where you should be setting the secrets, it's not using the .env file:

![image](https://user-images.githubusercontent.com/65402/71523000-57829500-28c7-11ea-9b08-70e60148d674.png)
![Screenshot_2019-12-24_at_17 57 50](https://user-images.githubusercontent.com/65402/71523001-57829500-28c7-11ea-954a-ff74459ffdb7.png)

I'm closing for now, but please be in touch if the problem persists.
